### ISSUE TITLE
Install in QGIS version 3.22.4-Białowieża

### ISSUE THREAD

**Issue by dpoursanidis** [SMByC/ArrNorm-Qgis-processing#2]
Hi,

Am trying to install in QGIS but error appear as below:

Couldn't load plugin 'ArrNorm-Qgis-processing-main' 

ModuleNotFoundError: No module named 'ArrNorm' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ArrNorm-Qgis-processing-main\__init__.py", line 25, in 
    from ArrNorm.utils.extra_deps import load_install_extra_deps, WaitDialog
  File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ArrNorm'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.4-Białowieża Białowieża, ce8e65e9 

Do i run something wrong?

**Comment by XavierCLL** [comment]
Hi @dpoursanidis 

Thanks for reporting it! please try again with a new minor version 22.5.24 that I've pushed in the Qgis plugins:

Note that due to some dlls that the plugin has, in windows: for update the plugin, you must first deactivate, restart Qgis, update and activate it.

Xavier

**Comment by tomas4** [comment]
I have a possibly related problem in QGIS 3.30.1-'s-Hertogenbosch on Linux. Trying to install throws error below, the plugin shows as installed afterwards, but throws the same error when trying to run it. I have tried to install osgeo and osgeo-utils with pip, but osgeo tells me it is just a placeholder for package gdal (gdal is installed) and I should  "update my application dependencies". osgeo-utils fails to install.


`ModuleNotFoundError: No module named 'osgeo_utils' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ArrNorm/__init__.py", line 32, in classFactory
    from ArrNorm.ArrNorm_plugin import ArrNormPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ArrNorm/ArrNorm_plugin.py", line 28, in 
    from ArrNorm.ArrNorm_provider import ArrNormProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ArrNorm/ArrNorm_provider.py", line 25, in 
    from ArrNorm.ArrNorm_algorithm import ArrNormAlgorithm
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ArrNorm/ArrNorm_algorithm.py", line 29, in 
    from ArrNorm.core.arrnorm import Normalization
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ArrNorm/core/arrnorm.py", line 25, in 
    from osgeo_utils.gdal_calc import Calc as gdal_calc
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osgeo_utils'


Verze Pythonu: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] 
QGIS verze: 3.30.1-'s-Hertogenbosch 's-Hertogenbosch, 447e8d717a 

Python cesta:
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/OpenTopography-DEM-Downloader
/usr/share/qgis/python
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/tom/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/tom/.local/share/QGIS/QGIS3/profiles/default/python/plugins`

**Comment by XavierCLL** [comment]
Hi @tomas4 is weird that your Qgis installation doesn't have the gdal-utils by default, however, I just included it in the plugin. Could you please check the latest version 23.4b uploaded in the Qgis repository? (keep in mind the Note 2 in [readme](https://github.com/SMByC/ArrNorm-Qgis-processing#arrnorm)), commit related [e770fda](https://github.com/SMByC/ArrNorm-Qgis-processing/commit/e770fda76c35d2427387c783fdcf3acc274ca81e)

**Comment by XavierCLL** [comment]
Issues fixed in the latest version, otherwise open it again.
